# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies including dev for build
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts
COPY . .
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy build artifacts
COPY --from=builder /app/build ./build

ENV NODE_ENV=production

ENTRYPOINT ["node", "build/index.js"]
CMD []
